name: CI
on: [push, pull_request]

jobs:
  ci:
    name: verify fmt/lints/build/tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo build --release
      - run: cargo test --all-features
